name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Authenticate using the GCP service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # ✅ Set up the gcloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    # ✅ Build and push Docker image
    - name: Build and Push to Google Container Registry
      run: |
        IMAGE="gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE_NAME }}"
        gcloud builds submit --tag $IMAGE

    # ✅ Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        IMAGE="gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE_NAME }}"
        gcloud run deploy ${{ secrets.SERVICE_NAME }} \
          --image $IMAGE \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
